name: test tree-sitter-stan

on:
  push:
    branches: [main]
    paths:
      - grammars/**/grammar.js
      - grammars/**/src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammars/**/grammar.js
      - grammars/**/src/**
      - bindings/**
      - binding.gyp
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - uses: tree-sitter/parser-test-action@v3
        with:
          abi-version: 14
          test-rust: true
          test-python: true
          test-go: true
          go-version: "1.23"
          test-node: true
          node-version: "20"
          test-swift: true
