name: test tree-sitter-stan
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - uses: tree-sitter/parser-test-action@v3
        with:
          abi-version: 14
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true
